name: code analysis

on:
  push:
    branches:
      - master
    pull request:

jobs:
  build:
    name: Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12
    - name: Analyse
      run: mvn sonar:sonar --file pom.xml
